lpp-31: impl task type
necodeIT/lb_planner_plugin pull request #42
Opened 2024-12-18 03:39 UTC by RiedleroD

most of this code was actually @Muhiiii 's, I just recycled it. Let's hope this even works 😓 all of this is poorly documented and confusing to me.

2024-12-18 03:50 UTC, RiedleroD commented
changes should now be on the testserver. I don't expect this to work first try though

2024-12-19 15:31 UTC, mcquenji commented
seems to be working, however there is an empty option?

![image](https://github.com/user-attachments/assets/e7b68815-ddd1-47cb-949d-7ad7b89ccb87)

and `SA` is missing

2024-12-19 16:44 UTC, mcquenji requested changes
seems to be working, however there is an empty option?

![image](https://github.com/user-attachments/assets/e7b68815-ddd1-47cb-949d-7ad7b89ccb87)

2025-01-03 11:30 UTC, RiedleroD commented
the empty option is moodle being moodle. Best I can do is select empty as default and hope people interpret it as "this field is empty atm, but you need to set it to a value"

2025-01-03 11:38 UTC, RiedleroD commented
merge blocked by #43 because we modify some imports

2025-01-03 11:55 UTC, mcquenji approved these changes

2025-01-03 11:57 UTC, merged